name: DCO Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dco-check:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - name: DCO Check
        uses: lcarva/dco-check@8943647f5d6a89c89420b925b6826649f87c95e1 # v3.2.0
        with:
          allow_merge_commits: true
